compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
num_machines: 1
machine_rank: 0
num_processes: 8  # Number of GPUs (processes)
use_cpu: false
gpu_ids: "0,1,2,3,4,5,6,7"  # The specific GPU IDs to use

